name: Generate CSR, Save Key to Azure Key Vault, and Upload CSR to Blob Storage

on:
  push:

jobs:
  generate-csr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenSSL
      run: sudo apt-get install -y openssl

    - name: Generate private key and CSR
      run: |
        # Generate a private key using RSA
        openssl genpkey -algorithm RSA -out private.key

        # Generate CSR
        openssl req -new -key private.key -out request.csr -subj "/CN=example.com"

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload private key to Azure Key Vault
      run: |
        # Upload private key to Azure Key Vault
        az keyvault secret set --vault-name ${{ secrets.AZURE_VAULT_NAME }} --name private-key --file private.key

    - name: Upload CSR to Azure Blob Storage
      run: |
        # Set the Azure storage account name and container name
        STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT }}
        CONTAINER_NAME=${{ secrets.AZURE_CONTAINER_NAME }}
        
        # Upload CSR to Blob Storage
        az storage blob upload --account-name $STORAGE_ACCOUNT_NAME --container-name $CONTAINER_NAME --name request.csr --file request.csr --auth-mode key --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}

    - name: Clean up local files
      run: |
        # Clean up the private key and CSR files
        rm -f private.key request.csr

