testing name: Process CSR Files

on:
  push:
    paths:
      - '**/*.csr'

jobs:
  process-csrs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process CSR files
        id: process-csrs
        run: |
          # Create temporary files for storing results
          echo "[]" > new_csrs.json
          echo "[]" > duplicate_csrs.json
          
          # Process all CSR files in the repository
          find . -name "*.csr" -type f | while read -r csr_file; do
            # Extract CSR information
            subject=$(openssl req -in "$csr_file" -noout -subject 2>/dev/null)
            pubkey=$(openssl req -in "$csr_file" -noout -pubkey 2>/dev/null | openssl md5 | cut -d' ' -f2)
            
            if [ -n "$subject" ]; then
              # Create JSON object for current CSR
              csr_info=$(jq -n \
                --arg file "$csr_file" \
                --arg subject "$subject" \
                --arg pubkey "$pubkey" \
                --arg date "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
                '{file: $file, subject: $subject, pubkey: $pubkey, date: $date}')
              
              # Check for duplicates in existing database
              is_duplicate=$(jq --argjson csr "$csr_info" '.csrs[] | select(.pubkey == $csr.pubkey or .subject == $csr.subject)' .github/csr_db.json)
              
              if [ -n "$is_duplicate" ]; then
                echo "$csr_info" | jq -c '.' >> duplicate_csrs.json
              else
                echo "$csr_info" | jq -c '.' >> new_csrs.json
              fi
            fi
          done
          # Set output for duplicates found
          if [ -s duplicate_csrs.json ]; then
            echo "::set-output name=duplicates_found::true"
          else
            echo "::set-output name=duplicates_found::false"
          fi
