name: Call Discord Notification

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Example 1: With custom message
  notify-custom:
    uses: phillabs/notify-discord/.github/workflows/discord-notify.yml@main
    with:
      message: |
        🔔 New ${{ github.event_name }} on ${{ github.repository }}
        **Branch:** ${{ github.ref }}
        **Actor:** ${{ github.actor }}
      title: "Repository Update"
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  # Example 2: Using defaults
  notify-default:
    uses: phillabs/notify-discord/.github/workflows/discord-notify.yml@main
    with:
      repository: ${{ github.repository }}
      event: ${{ github.event_name }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}