name: Call Discord Notification

on:
  push:
    branches: [ main ]
  # Optional: Add manual trigger
  workflow_dispatch:
    inputs:
      custom-message:
        description: 'Custom message to send'
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Call Discord Notification
        uses: phillabs/notify-discord/.github/workflows/v3-discord-notification.yml@main
        with:
          message: |
            🔔 New ${{ github.event_name }} on ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Actor:** ${{ github.actor }}
          title: "Repository Update"
          color: "5865F2"  # Discord Blue
        secrets:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
