name: Call Discord Notification

on:
  # Define your triggers here
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Manual trigger
  workflow_dispatch:
    inputs:
      custom-message:
        description: 'Custom message to send'
        required: false
        type: string

jobs:
  call-discord:
    runs-on: ubuntu-latest
    steps:
      # Optional: Checkout if you need repository content
      - uses: actions/checkout@v3

      # Call the reusable workflow
      - name: Call Discord Notification
        uses: ./.github/workflows/discord-notification.yml@main  # Replace with your repository reference
        with:
          message: |
            ${{ github.event.inputs.custom-message || format('
              🔔 New {0} on {1}
              **Branch:** {2}
              **Actor:** {3}
              **Commit:** {4}
            ', github.event_name, github.repository, github.ref, github.actor, github.event.head_commit.message) }}
          title: "Repository Update"
          color: "5865F2"  # Discord Blue
        secrets:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}