name: Complex Workflow with Discord Notification

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build step
        id: build
        run: |
          # Your build steps here
          echo "build_status=success" >> $GITHUB_OUTPUT

  notify:
    needs: build
    uses: phillabs/notify-discord/.github/workflows/discord-notification.yml@main
    with:
      message: |
        **Build Status:** ${{ needs.build.outputs.build_status }}
        **Repository:** ${{ github.repository }}
        **Commit:** ${{ github.event.head_commit.message }}
        **Author:** ${{ github.actor }}
        
        [View Build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
      title: "Build Notification"
      color: ${{ needs.build.outputs.build_status == 'success' && '00FF00' || 'FF0000' }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}